#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -f -- ~/.profile
rm -f -- ~/.bashrc
rm -f -- ~/.bash_logout
rm -f -- ~/.vimrc
rm -f -- ~/.gitconfig
mkdir -p ~/.vim
mkdir -p ~/.jupyter
mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/apputils-extension
mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/fileeditor-extension
mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/notebook-extension
mkdir -p ~/.config/htop

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
